### ISSUE TITLE
Compagnon breaks boxesandglue

### ISSUE THREAD

**Issue by drj11** [boxesandglue/textlayout#2]
Trying to use the font Compagnon Medium (from Velvetyne: https://velvetyne.fr/download/?font=compagnon ) breaks boxesandglue.

I haven't investigated, but the error message suggests a problem with not enough operands in the charstring at some point.

```
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
github.com/boxesandglue/textlayout/fonts/type1C.(*type2state).popN(...)
	/Users/drj/prj/textlayout/fonts/type1C/type2charstring.go:42
github.com/boxesandglue/textlayout/fonts/type1C.getSubrsIndex(0x2a3, 0x258, {0xc00023e008, 0x7b, 0xaa}, {0xc000238c08, 0x7b, 0x7b}, {0xc000018330, 0x23, ...}, ...)
	/Users/drj/prj/textlayout/fonts/type1C/type2charstring.go:162 +0xff0
github.com/boxesandglue/textlayout/fonts/type1C.(*Font).Subset(0xc00017a008, {0xc000018e10, 0x9, 0xc000112210?})
	/Users/drj/prj/textlayout/fonts/type1C/font.go:532 +0x2c5
github.com/boxesandglue/textlayout/fonts/truetype.(*Font).subsetCFF(...)
	/Users/drj/prj/textlayout/fonts/truetype/subset.go:82
github.com/boxesandglue/textlayout/fonts/truetype.(*Font).Subset(0xc000172008, {0xc000018e10, 0x9, 0x9})
	/Users/drj/prj/textlayout/fonts/truetype/subset.go:209 +0xba
github.com/boxesandglue/baseline-pdf.(*Face).finish(0xc0000743c0)
	/Users/drj/go/pkg/mod/github.com/boxesandglue/baseline-pdf@v0.0.0-20240929173510-09d9762f7b3d/pdffont.go:170 +0x22e
github.com/boxesandglue/baseline-pdf.(*PDF).writeDocumentCatalogAndPages(0xc000116210)
	/Users/drj/go/pkg/mod/github.com/boxesandglue/baseline-pdf@v0.0.0-20240929173510-09d9762f7b3d/writer.go:468 +0x1d46
github.com/boxesandglue/baseline-pdf.(*PDF).Finish(0xc000116210)
	/Users/drj/go/pkg/mod/github.com/boxesandglue/baseline-pdf@v0.0.0-20240929173510-09d9762f7b3d/writer.go:537 +0x2a
main.dothings()
	/Users/drj/prj/boxesandglue-drj/baseline/font/main.go:62 +0x8e5
main.main()
	/Users/drj/prj/boxesandglue-drj/baseline/font/main.go:95 +0x13
```

[and don't worry, i'm not intending to do a comprehensive survey, these are just a couple of the fonts i use for personal testing]

**Comment by pgundlach** [comment]
Could you post your input file? I cannot reproduce the problem with my text.

(Any bug report is welcome!)

**Comment by drj11** [comment]
yeah, my text is `Dolphins` and i'm using my extended fontsexample again: https://gitlab.com/drj11/boxesandglue-examples/-/blob/main/baseline/font/main.go?ref_type=heads

So my command line is:

    ; ./fontsexample ~/prj/eft/Compagnon-Medium.otf

with Compagnon-Medium.otf from https://gitlab.com/drj11/eft (which was downloaded from Velvetyne, and i don't think it has changed since then).

**Comment by drj11** [comment]
Indeed, it must be a problem with particular glyphs, `Dolphins` does not work, but `ophins` is fine.

**Comment by pgundlach** [comment]
Thank you again. This is very helpful!
I have updated baseline-pdf and textlayout to version 1.0.1 each.
